# 
# Projekt IFJ - Interpret jazyka IFJ14
#
# Autori: Matúš Bútora
#		  Daniel Dušek
#		  Marie Faltusová
#		  Roman Jaška
#		  Filip Kalous
#
# Datum:  14.12.2014
#

CC=gcc										# prekladac jazyka C
CFLAGS=-std=c99 -Wall -pedantic     # parametry programu


main: main.c
	$(CC) $(CFLAGS) main.c -o main